import Head from "next/head";
import styles from "../../styles/Home.module.css";

import { useCallback, useEffect, useState } from "react";

import { CardPokemon } from "../../components/CardPokemon";

type PokemonObj = {
  id: number;
  name: string;
  imageFront: string;
  imageBack: string;
};

function Home({ pokemons, next }) {
  const [listPokemon, setListPokemon] = useState([]);
  const [nextUrl, setNextUrl] = useState(null);

  const getPokemons = useCallback(async () => {
    if (nextUrl) {
      await fetch(nextUrl)
        .then(res => res.json())
        .then(data => {
          console.log(">>> finish fetch");
          console.log(data)
          setNextUrl(data.next);

          const _pokemons = [...listPokemon, ...data.results];
          setListPokemon(_pokemons);
        });
    }
  }, [nextUrl]);

  useEffect(() => {
    if (listPokemon.length === 0) {
      setListPokemon(pokemons);
      setNextUrl(next);
    }
  }, [listPokemon, pokemons, next]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link rel="preconnect" href="https://fonts.gstatic.com"></link>
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <main className={styles.main}>
        <div className={styles.grid}>
          {listPokemon &&
            listPokemon.map((pokemon: PokemonObj) => (
              <CardPokemon key={pokemon.name} pokemon={pokemon} />
            ))}
        </div>

        <button
          className={styles.loading}
          onClick={getPokemons}
        >
          Carregar mais...
        </button>
      </main>
    </>
  );
}

export async function getServerSideProps(context) {
  const pokemonsData = await fetch(
    `https://pokeapi.co/api/v2/pokemon?limit=20`
  );
  const pokemons = await pokemonsData.json();

  return {
    props: {
      pokemons: pokemons.results,
      next: pokemons.next,
    },
  };
}

export default Home;
